# ============================================= #
#              Dice Configuration               #
#              By: ChickenSaysBak               #
#                                               #
# To reload, use /diceplugin reload             #
#                                               #
# Permissions:                                  #
# - dice.use (to use /roll)                     #
# - dice.admin (to use /diceplugin)             #
# ============================================= #

# Set how long in seconds a player must wait before rolling again.
cooldown: 10

# The amount of dice rolled if no amount is specified.
default_amount: 2

# The maximum amount of dice that can be rolled at a time.
maximum: 12

# The minimum amount of dice that can be rolled at a time.
minimum: 1